"""Editorial source for the reviewed launch pack. Assets are original institutional downloads."""
from pathlib import Path
import json,hashlib,subprocess
ROOT=Path(__file__).resolve().parents[1]
PACK=ROOT/'Packages/CelestialKit/Sources/CelestialKit/Resources/astronomy'
def t(zh,en,ko):return dict(zhHans=zh,en=en,ko=ko)
headings=[t('你正在看什么','What you are seeing','무엇을 보고 있나요'),t('留意这些细节','Look a little closer','자세히 살펴보기'),t('影像如何形成','How the image was made','이미지는 어떻게 만들어졌나요')]
def card(id,title,subtitle,caption,category,capture,credit,url,license,licenseURL,image,fit,sections):
 p=PACK/'assets'/image
 info=subprocess.check_output(['sips','-g','pixelWidth','-g','pixelHeight',str(p)],text=True)
 dims=[int(line.split(':')[-1]) for line in info.splitlines() if 'pixel' in line]
 return dict(id='sky-'+id,title=t(*title),subtitle=t(*subtitle),caption=t(*caption),category=t(*category),capture=t(*capture),credit=credit,sourceURL=url,license=license,licenseURL=licenseURL,image='assets/'+image,sha256=hashlib.sha256(p.read_bytes()).hexdigest(),width=dims[0],height=dims[1],fit=fit,sections=[dict(id=str(i+1),title=headings[i],text=t(*s[:3]),sourceURL=s[3] if len(s)>3 else url) for i,s in enumerate(sections)])
cards=[card('carina',('宇宙悬崖','Cosmic Cliffs','우주의 절벽'),('NGC 3324 · 韦伯空间望远镜','NGC 3324 · James Webb Space Telescope','NGC 3324 · 제임스 웹 우주망원경'),('年轻恒星的辐射与恒星风，正在雕刻这片气体与尘埃。','Young stars sculpt these clouds with radiation and stellar winds.','젊은 별의 복사와 항성풍이 가스와 먼지 구름을 조각하고 있습니다.'),('星云','Nebula','성운'),('近红外 · NIRCam','Near-infrared · NIRCam','근적외선 · NIRCam'),'NASA, ESA, CSA, and STScI','https://esawebb.org/images/weic2205a/','CC BY 4.0','https://esawebb.org/copyright/','carina.jpg',False,[
('这是船底座星云中 NGC 3324 恒星形成区的边缘，距离我们约 7,600 光年。看似山脊的结构，是巨大气体空腔的边界。','This is the edge of the star-forming region NGC 3324 in the Carina Nebula, about 7,600 light-years away. The apparent ridge marks the boundary of a vast gaseous cavity.','약 7,600광년 떨어진 용골자리 성운의 별 탄생 영역 NGC 3324 가장자리입니다. 산등성이처럼 보이는 구조는 거대한 가스 공동의 경계입니다.'),
('高温年轻恒星的辐射和恒星风侵蚀云壁，留下柱状结构。韦伯的近红外相机揭示了此前被尘埃遮蔽的恒星。','Radiation and winds from hot young stars erode the cloud wall, leaving pillars behind. Webb’s near-infrared camera reveals stars previously hidden by dust.','뜨겁고 젊은 별의 복사와 항성풍이 구름 벽을 깎아내며 기둥 모양의 구조를 남깁니다. 웹의 근적외선 카메라는 먼지에 가려져 있던 별들을 드러냅니다.'),
('不同红外波段被映射为可见颜色，帮助我们辨认肉眼无法直接看到的结构。图像来源于真实观测，颜色用于表达波段信息。','Different infrared wavelengths are mapped to visible colors, revealing structures our eyes cannot see directly. The image comes from real observations; its colors represent wavelength information.','서로 다른 적외선 파장을 눈에 보이는 색으로 표현해 맨눈으로 볼 수 없는 구조를 드러냅니다. 실제 관측 자료로 만든 이미지이며, 색은 파장 정보를 나타냅니다.','https://esawebb.org/about/general/image-processing/')]),
card('saturn',('土星与它的环','Saturn & Its Rings','토성과 고리'),('土星 · 卡西尼号探测器','Saturn · Cassini spacecraft','토성 · 카시니 탐사선'),('这幅土星肖像，由卡西尼号拍摄的 126 张影像拼接而成。','A portrait assembled from 126 images captured by Cassini.','카시니가 촬영한 이미지 126장을 이어 붙여 만든 토성의 초상입니다.'),('行星','Planet','행성'),('可见光 · 自然色合成','Visible light · Natural-color mosaic','가시광선 · 자연색 모자이크'),'NASA/JPL/Space Science Institute','https://science.nasa.gov/resource/the-greatest-saturn-portraityet/','NASA Media Guidelines','https://www.nasa.gov/nasa-brand-center/images-and-media/','saturn.jpg',True,[
('2004 年 10 月 6 日，卡西尼号在约 630 万千米外拍摄土星。42 个取景区域各拍红、绿、蓝三幅图像，组成这幅自然色全景。','On October 6, 2004, Cassini imaged Saturn from about 6.3 million kilometers away. Red, green and blue exposures at each of 42 positions form this natural-color mosaic.','2004년 10월 6일, 카시니는 약 630만 킬로미터 거리에서 토성을 촬영했습니다. 42개 영역에서 각각 빨강·초록·파랑 필터로 촬영한 이미지로 자연색 모자이크를 만들었습니다.'),
('观察土星在环上投下的阴影，以及环在行星上留下的阴影。环带之间的细微色差，也保留在这幅影像里。','Look for the planet’s shadow across its rings, and the rings’ shadows on the planet. Subtle color differences across the rings are also visible.','고리 위에 드리운 토성의 그림자와 토성에 비친 고리의 그림자를 찾아보세요. 고리 사이의 미묘한 색 차이도 볼 수 있습니다.'),
('每个取景区域的红、绿、蓝图像先合成为彩色影像，再拼成完整肖像。这些照片在约两小时内拍摄。','The red, green and blue exposures at each position were combined into color images, then assembled into the complete portrait. The images were taken over about two hours.','각 영역의 빨강·초록·파랑 이미지를 컬러 이미지로 합친 뒤 전체 초상으로 이어 붙였습니다. 촬영에는 약 두 시간이 걸렸습니다.')]),
card('milkyway',('帕拉纳尔的银河','Milky Way over Paranal','파라날의 은하수'),('智利 · 帕拉纳尔天文台','Chile · Paranal Observatory','칠레 · 파라날 천문대'),('银河明亮的中央区域，被一道道深色尘埃带穿过。','Dark dust lanes cross the bright central region of our galaxy.','어두운 먼지 띠가 우리 은하의 밝은 중심부를 가로지릅니다.'),('地面星空','Night sky','밤하늘'),('地面摄影 · 可见光','Ground-based photography · Visible light','지상 사진 · 가시광선'),'G. Hüdepohl (atacamaphoto.com)/ESO','https://www.eso.org/public/images/gerd_huedepohl_7/','CC BY 4.0','https://www.eso.org/public/outreach/copyright/','milkyway.jpg',False,[
('银河铺展在智利帕拉纳尔山上空，地平线处是甚大望远镜的剪影。最明亮、被深色条带穿过的区域，对应银河系的中央核球。','The Milky Way stretches above Cerro Paranal in Chile, with the Very Large Telescope silhouetted on the horizon. The brightest area, crossed by dark lanes, corresponds to our galaxy’s central bulge.','칠레 파라날산 위로 은하수가 펼쳐지고, 지평선에는 초거대망원경의 실루엣이 보입니다. 어두운 띠가 가로지르는 가장 밝은 부분은 우리 은하의 중심 팽대부입니다.'),
('银河中央附近还有一柱较明亮的黄道光。沿着深色尘埃带寻找结构，可以看见星空中明暗交错的层次。','A brighter column of zodiacal light intersects the central region. Follow the dark dust lanes to explore the alternating bright and dark structures.','밝은 황도광 기둥이 은하 중심부와 교차합니다. 어두운 먼지 띠를 따라가며 밝고 어두운 구조가 이루는 층을 살펴보세요.'),
('这是一张地面夜空摄影，保留了天文台所在山脊和前景岩石。拍摄器材与曝光参数未在来源页列出。','This ground-based night photograph includes the observatory’s ridge and foreground rocks. Camera and exposure details are not listed on the source page.','천문대가 있는 산등성이와 앞쪽 바위를 함께 담은 지상 밤하늘 사진입니다. 출처 페이지에는 카메라와 노출 정보가 나와 있지 않습니다.')])]
(PACK/'catalog.json').write_text(json.dumps(dict(schemaVersion=1,version='1.0.0',cards=cards),ensure_ascii=False,indent=2)+'\n')
print('Created trilingual astronomy pack:',len(cards),'cards')
